import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "NextJS Tutorial",
    template: "%s | Tutorial Beginner",
  },
  description: "Generated by NextJS"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <header 
      style={{
        backgroundColor: "lightblue",
        padding: "1rem",
      }}>
        <p>Header</p>
      </header>
      {children}
      <footer
        style={{ 
          backgroundColor: "ghostwhite",
          padding: "1rem",
          textAlign: "center",
          color: "black",
        }}>
        <p>Footer</p>
      </footer>
      </body>
    </html>
  );
}
